//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coworking.WebApi.Resources.Pages.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _RoomFilter {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _RoomFilter() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coworking.WebApi.Resources.Pages.Shared._RoomFilter", typeof(_RoomFilter).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата заезда.
        /// </summary>
        internal static string DateFromLabel {
            get {
                return ResourceManager.GetString("DateFromLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выезда.
        /// </summary>
        internal static string DateToLabel {
            get {
                return ResourceManager.GetString("DateToLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найти.
        /// </summary>
        internal static string FindButton {
            get {
                return ResourceManager.GetString("FindButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to от.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гостей.
        /// </summary>
        internal static string GuestsLabel {
            get {
                return ResourceManager.GetString("GuestsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        internal static string GuestsPlaceholder {
            get {
                return ResourceManager.GetString("GuestsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по названию или удобствам….
        /// </summary>
        internal static string NameValueSearchFullPlaceholder {
            get {
                return ResourceManager.GetString("NameValueSearchFullPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена за час.
        /// </summary>
        internal static string PriceLabel {
            get {
                return ResourceManager.GetString("PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить фильтры.
        /// </summary>
        internal static string ResetFilterLink {
            get {
                return ResourceManager.GetString("ResetFilterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По удобствам.
        /// </summary>
        internal static string SortAmenities {
            get {
                return ResourceManager.GetString("SortAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По вместимости.
        /// </summary>
        internal static string SortCapacity {
            get {
                return ResourceManager.GetString("SortCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to По умолчанию.
        /// </summary>
        internal static string SortDefault {
            get {
                return ResourceManager.GetString("SortDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала новые.
        /// </summary>
        internal static string SortNewest {
            get {
                return ResourceManager.GetString("SortNewest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сначала старые.
        /// </summary>
        internal static string SortOldest {
            get {
                return ResourceManager.GetString("SortOldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена: по возрастанию.
        /// </summary>
        internal static string SortPriceAsc {
            get {
                return ResourceManager.GetString("SortPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена: по убыванию.
        /// </summary>
        internal static string SortPriceDesc {
            get {
                return ResourceManager.GetString("SortPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
    }
}
