//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coworking.WebApi.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coworking.WebApi.Resources.Pages.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алексей.
        /// </summary>
        internal static string FounderName {
            get {
                return ResourceManager.GetString("FounderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основатель.
        /// </summary>
        internal static string FounderRole {
            get {
                return ResourceManager.GetString("FounderRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы создали место, где рождаются идеи..
        /// </summary>
        internal static string HistoryLead {
            get {
                return ResourceManager.GetString("HistoryLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coworking Space начался с простой идеи: предоставить фрилансерам и стартапам профессиональное окружение без долгосрочных обязательств по аренде офиса. Сегодня мы — дом для более чем 200 резидентов..
        /// </summary>
        internal static string HistoryText {
            get {
                return ResourceManager.GetString("HistoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша история.
        /// </summary>
        internal static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мария.
        /// </summary>
        internal static string ManagerName {
            get {
                return ResourceManager.GetString("ManagerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комьюнити-менеджер.
        /// </summary>
        internal static string ManagerRole {
            get {
                return ResourceManager.GetString("ManagerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставить каждому предпринимателю инструменты для роста. Мы верим, что правильное окружение ускоряет развитие бизнеса в 2 раза..
        /// </summary>
        internal static string MissionText {
            get {
                return ResourceManager.GetString("MissionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша миссия.
        /// </summary>
        internal static string MissionTitle {
            get {
                return ResourceManager.GetString("MissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О нас.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наша команда.
        /// </summary>
        internal static string TeamTitle {
            get {
                return ResourceManager.GetString("TeamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комфорт: Эргономичная мебель и тишина..
        /// </summary>
        internal static string ValueComfort {
            get {
                return ResourceManager.GetString("ValueComfort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Развитие: Мы поддерживаем обучение и рост..
        /// </summary>
        internal static string ValueGrowth {
            get {
                return ResourceManager.GetString("ValueGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открытость: Мы открыты для новых идей и людей..
        /// </summary>
        internal static string ValueOpenness {
            get {
                return ResourceManager.GetString("ValueOpenness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наши ценности.
        /// </summary>
        internal static string ValuesTitle {
            get {
                return ResourceManager.GetString("ValuesTitle", resourceCulture);
            }
        }
    }
}
