//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coworking.WebApi.Resources.Pages {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coworking.WebApi.Resources.Pages.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неограниченный доступ к кофе-машине, чаю и печенью для всех резидентов..
        /// </summary>
        internal static string FeatureCoffeeDesc {
            get {
                return ResourceManager.GetString("FeatureCoffeeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бесплатный Кофе.
        /// </summary>
        internal static string FeatureCoffeeTitle {
            get {
                return ResourceManager.GetString("FeatureCoffeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регулярные нетворки-сессии, мастер-классы и встречи с единомышленниками..
        /// </summary>
        internal static string FeatureCommunityDesc {
            get {
                return ResourceManager.GetString("FeatureCommunityDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комьюнити.
        /// </summary>
        internal static string FeatureCommunityTitle {
            get {
                return ResourceManager.GetString("FeatureCommunityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оптоволоконный канал 1 Гбит/с и резервное питание для бесперебойной работы..
        /// </summary>
        internal static string FeatureInternetDesc {
            get {
                return ResourceManager.GetString("FeatureInternetDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скоростной Интернет.
        /// </summary>
        internal static string FeatureInternetTitle {
            get {
                return ResourceManager.GetString("FeatureInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Центр города с легким доступом к общественному транспорту и парковке..
        /// </summary>
        internal static string FeatureLocationDesc {
            get {
                return ResourceManager.GetString("FeatureLocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удобное Расположение.
        /// </summary>
        internal static string FeatureLocationTitle {
            get {
                return ResourceManager.GetString("FeatureLocationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Современные рабочие зоны в самом центре города..
        /// </summary>
        internal static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать в бронирование коворкинга.
        /// </summary>
        internal static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мы создаем идеальное пространство для вашего бизнеса и творчества.
        /// </summary>
        internal static string WhyUsSubtitle {
            get {
                return ResourceManager.GetString("WhyUsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почему выбирают нас?.
        /// </summary>
        internal static string WhyUsTitle {
            get {
                return ResourceManager.GetString("WhyUsTitle", resourceCulture);
            }
        }
    }
}
