//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coworking.WebApi.Resources.Pages {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Details {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Details() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coworking.WebApi.Resources.Pages.Details", typeof(Details).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступность:.
        /// </summary>
        internal static string AvailabilityLabel {
            get {
                return ResourceManager.GetString("AvailabilityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24/7.
        /// </summary>
        internal static string AvailabilityValue {
            get {
                return ResourceManager.GetString("AvailabilityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забронировать сейчас.
        /// </summary>
        internal static string BookNowButton {
            get {
                return ResourceManager.GetString("BookNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вместимость:.
        /// </summary>
        internal static string CapacityLabel {
            get {
                return ResourceManager.GetString("CapacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристики.
        /// </summary>
        internal static string CharacteristicsTitle {
            get {
                return ResourceManager.GetString("CharacteristicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить бронирование.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пт.
        /// </summary>
        internal static string DayFri {
            get {
                return ResourceManager.GetString("DayFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пн.
        /// </summary>
        internal static string DayMon {
            get {
                return ResourceManager.GetString("DayMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сб.
        /// </summary>
        internal static string DaySat {
            get {
                return ResourceManager.GetString("DaySat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вс.
        /// </summary>
        internal static string DaySun {
            get {
                return ResourceManager.GetString("DaySun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чт.
        /// </summary>
        internal static string DayThu {
            get {
                return ResourceManager.GetString("DayThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вт.
        /// </summary>
        internal static string DayTue {
            get {
                return ResourceManager.GetString("DayTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ср.
        /// </summary>
        internal static string DayWed {
            get {
                return ResourceManager.GetString("DayWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        internal static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч.
        /// </summary>
        internal static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение:.
        /// </summary>
        internal static string LocationLabel {
            get {
                return ResourceManager.GetString("LocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главный корпус.
        /// </summary>
        internal static string LocationValue {
            get {
                return ResourceManager.GetString("LocationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование.
        /// </summary>
        internal static string ModalTitleLabel {
            get {
                return ResourceManager.GetString("ModalTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали комнаты.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to человек.
        /// </summary>
        internal static string PeopleLabel {
            get {
                return ResourceManager.GetString("PeopleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / час.
        /// </summary>
        internal static string PricePerHourLabel {
            get {
                return ResourceManager.GetString("PricePerHourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип помещения:.
        /// </summary>
        internal static string RoomTypeLabel {
            get {
                return ResourceManager.GetString("RoomTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рабочая зона.
        /// </summary>
        internal static string RoomTypeValue {
            get {
                return ResourceManager.GetString("RoomTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дату.
        /// </summary>
        internal static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        internal static string SelectTimeLabel {
            get {
                return ResourceManager.GetString("SelectTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование подтверждено!.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        internal static string SummaryDatetimeLabel {
            get {
                return ResourceManager.GetString("SummaryDatetimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность.
        /// </summary>
        internal static string SummaryDurationLabel {
            get {
                return ResourceManager.GetString("SummaryDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        internal static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
    }
}
