//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coworking.WebApi.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Room {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Room() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Coworking.WebApi.Resources.Pages.Rooms.Room", typeof(Room).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забронировать.
        /// </summary>
        internal static string BookButton {
            get {
                return ResourceManager.GetString("BookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чел..
        /// </summary>
        internal static string CapacityLabel {
            get {
                return ResourceManager.GetString("CapacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить бронирование.
        /// </summary>
        internal static string ConfirmButton {
            get {
                return ResourceManager.GetString("ConfirmButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пт.
        /// </summary>
        internal static string DayFri {
            get {
                return ResourceManager.GetString("DayFri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пн.
        /// </summary>
        internal static string DayMon {
            get {
                return ResourceManager.GetString("DayMon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сб.
        /// </summary>
        internal static string DaySat {
            get {
                return ResourceManager.GetString("DaySat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вс.
        /// </summary>
        internal static string DaySun {
            get {
                return ResourceManager.GetString("DaySun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to чт.
        /// </summary>
        internal static string DayThu {
            get {
                return ResourceManager.GetString("DayThu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to вт.
        /// </summary>
        internal static string DayTue {
            get {
                return ResourceManager.GetString("DayTue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ср.
        /// </summary>
        internal static string DayWed {
            get {
                return ResourceManager.GetString("DayWed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продолжительность.
        /// </summary>
        internal static string DurationLabel {
            get {
                return ResourceManager.GetString("DurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Попробуйте изменить параметры поиска или.
        /// </summary>
        internal static string EmptyStateText {
            get {
                return ResourceManager.GetString("EmptyStateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string FilterButton {
            get {
                return ResourceManager.GetString("FilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Найдено:.
        /// </summary>
        internal static string FindTitle {
            get {
                return ResourceManager.GetString("FindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Современные рабочие зоны в самом центре города. Бронируйте онлайн за пару кликов..
        /// </summary>
        internal static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пространство для творчества.
        /// </summary>
        internal static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ч.
        /// </summary>
        internal static string HourLabel {
            get {
                return ResourceManager.GetString("HourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Макс. цена.
        /// </summary>
        internal static string MaxPriceLabel {
            get {
                return ResourceManager.GetString("MaxPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. вместимость.
        /// </summary>
        internal static string MinCapacityLabel {
            get {
                return ResourceManager.GetString("MinCapacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мин. цена.
        /// </summary>
        internal static string MinPriceLabel {
            get {
                return ResourceManager.GetString("MinPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование.
        /// </summary>
        internal static string ModalTitleLabel {
            get {
                return ResourceManager.GetString("ModalTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В данный момент все комнаты заняты или недоступны..
        /// </summary>
        internal static string NoRoomsMessage {
            get {
                return ResourceManager.GetString("NoRoomsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коворкинг - Доступные зоны.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to в час.
        /// </summary>
        internal static string PricePerHourLabel {
            get {
                return ResourceManager.GetString("PricePerHourLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сбросить фильтры.
        /// </summary>
        internal static string ResetFiltersLink {
            get {
                return ResourceManager.GetString("ResetFiltersLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to залов.
        /// </summary>
        internal static string RoomsTitle {
            get {
                return ResourceManager.GetString("RoomsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to зал.
        /// </summary>
        internal static string RoomTitle {
            get {
                return ResourceManager.GetString("RoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск по названию или описанию....
        /// </summary>
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступные зоны.
        /// </summary>
        internal static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите дату.
        /// </summary>
        internal static string SelectDateLabel {
            get {
                return ResourceManager.GetString("SelectDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        internal static string SelectTimeLabel {
            get {
                return ResourceManager.GetString("SelectTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бронирование подтверждено!.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        internal static string SummaryDatetimeLabel {
            get {
                return ResourceManager.GetString("SummaryDatetimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Длительность.
        /// </summary>
        internal static string SummaryDurationLabel {
            get {
                return ResourceManager.GetString("SummaryDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Итого.
        /// </summary>
        internal static string TotalLabel {
            get {
                return ResourceManager.GetString("TotalLabel", resourceCulture);
            }
        }
    }
}
